/// An alarm that carries its own tone choice.
///
/// [key] is both the storage-key suffix and the asset-name prefix of the
/// generated tones; [classicAsset] is the original long tone, which low warning
/// and low urgent (and the two highs) still share.
enum AlarmSlot {
  lowWarning('low_warning', 'alarm_low'),
  lowUrgent('low_urgent', 'alarm_low'),
  highWarning('high_warning', 'alarm_high'),
  highUrgent('high_urgent', 'alarm_high'),
  advisoryLow('advisory_low', 'alarm_low_soon'),
  advisoryHigh('advisory_high', 'alarm_high_soon');

  const AlarmSlot(this.key, this.classicAsset);

  final String key;
  final String classicAsset;

  String get labelKey => 'profile.alarmtone.slot.$key';
}

/// The tone styles an alarm can be set to.
///
/// Every style encodes the alarm type the same way (falling notes = low, rising
/// = high, two motifs = warning, three = urgent, a single glide = pre-warning),
/// so a short tone still says which alarm is standing and mixing styles across
/// alarms stays unambiguous. `classic` is the original long tone and the
/// default; `short` and `ping` are generated by `tool/generate_alarm_tones.py`
/// and last under a second. `off` silences THIS alarm alone, leaving the others
/// audible — the global [ProfileAlarmSoundState] toggle silences all of them.
enum AlarmTone {
  classic,
  short,
  ping,
  off;

  String get labelKey => 'profile.alarmtone.tone.$name';

  /// The asset this style plays for [slot], or null when it plays nothing.
  String? assetFor(AlarmSlot slot) {
    return switch (this) {
      AlarmTone.off => null,
      AlarmTone.classic => 'sounds/${slot.classicAsset}.wav',
      AlarmTone.short || AlarmTone.ping => 'sounds/${slot.key}_$name.wav',
    };
  }
}
