// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/jpake.dart';
import 'api/simple.dart';
import 'api/x25519.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1376232026;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_insulink',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Uint8List crateApiJpakeG7JpakeAes8({
    required G7Jpake that,
    required List<int> data8,
  });

  G7Jpake crateApiJpakeG7JpakeNew({required String pairingCode});

  Uint8List crateApiJpakeG7JpakePopSign({
    required G7Jpake that,
    required List<int> challenge,
    required List<int> displayKey,
  });

  Uint8List crateApiJpakeG7JpakeRound1Payload({required G7Jpake that});

  Uint8List crateApiJpakeG7JpakeRound2Payload({required G7Jpake that});

  Uint8List crateApiJpakeG7JpakeRound3Payload({required G7Jpake that});

  bool crateApiJpakeG7JpakeSetSensorRound1({
    required G7Jpake that,
    required List<int> payload,
  });

  bool crateApiJpakeG7JpakeSetSensorRound2({
    required G7Jpake that,
    required List<int> payload,
  });

  Uint8List crateApiJpakeG7JpakeSetSensorRound3({
    required G7Jpake that,
    required List<int> payload,
  });

  Uint8List crateApiJpakeG7JpakeSharedKey({required G7Jpake that});

  Uint8List crateApiJpakeAes8WithKey({
    required List<int> sessionKey,
    required List<int> data8,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Uint8List crateApiX25519X25519GeneratePrivateKey();

  Uint8List crateApiX25519X25519PublicFromPrivate({
    required List<int> privateKey,
  });

  Uint8List crateApiX25519X25519SharedSecret({
    required List<int> privateKey,
    required List<int> peerPublicKey,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_G7Jpake;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_G7Jpake;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_G7JpakePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Uint8List crateApiJpakeG7JpakeAes8({
    required G7Jpake that,
    required List<int> data8,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(data8, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeG7JpakeAes8ConstMeta,
        argValues: [that, data8],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeAes8ConstMeta => const TaskConstMeta(
    debugName: "G7Jpake_aes8",
    argNames: ["that", "data8"],
  );

  @override
  G7Jpake crateApiJpakeG7JpakeNew({required String pairingCode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pairingCode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeG7JpakeNewConstMeta,
        argValues: [pairingCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeNewConstMeta =>
      const TaskConstMeta(debugName: "G7Jpake_new", argNames: ["pairingCode"]);

  @override
  Uint8List crateApiJpakeG7JpakePopSign({
    required G7Jpake that,
    required List<int> challenge,
    required List<int> displayKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(challenge, serializer);
          sse_encode_list_prim_u_8_loose(displayKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeG7JpakePopSignConstMeta,
        argValues: [that, challenge, displayKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakePopSignConstMeta =>
      const TaskConstMeta(
        debugName: "G7Jpake_pop_sign",
        argNames: ["that", "challenge", "displayKey"],
      );

  @override
  Uint8List crateApiJpakeG7JpakeRound1Payload({required G7Jpake that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJpakeG7JpakeRound1PayloadConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeRound1PayloadConstMeta =>
      const TaskConstMeta(
        debugName: "G7Jpake_round1_payload",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiJpakeG7JpakeRound2Payload({required G7Jpake that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiJpakeG7JpakeRound2PayloadConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeRound2PayloadConstMeta =>
      const TaskConstMeta(
        debugName: "G7Jpake_round2_payload",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiJpakeG7JpakeRound3Payload({required G7Jpake that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeG7JpakeRound3PayloadConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeRound3PayloadConstMeta =>
      const TaskConstMeta(
        debugName: "G7Jpake_round3_payload",
        argNames: ["that"],
      );

  @override
  bool crateApiJpakeG7JpakeSetSensorRound1({
    required G7Jpake that,
    required List<int> payload,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(payload, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeG7JpakeSetSensorRound1ConstMeta,
        argValues: [that, payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeSetSensorRound1ConstMeta =>
      const TaskConstMeta(
        debugName: "G7Jpake_set_sensor_round1",
        argNames: ["that", "payload"],
      );

  @override
  bool crateApiJpakeG7JpakeSetSensorRound2({
    required G7Jpake that,
    required List<int> payload,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(payload, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeG7JpakeSetSensorRound2ConstMeta,
        argValues: [that, payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeSetSensorRound2ConstMeta =>
      const TaskConstMeta(
        debugName: "G7Jpake_set_sensor_round2",
        argNames: ["that", "payload"],
      );

  @override
  Uint8List crateApiJpakeG7JpakeSetSensorRound3({
    required G7Jpake that,
    required List<int> payload,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(payload, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeG7JpakeSetSensorRound3ConstMeta,
        argValues: [that, payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeSetSensorRound3ConstMeta =>
      const TaskConstMeta(
        debugName: "G7Jpake_set_sensor_round3",
        argNames: ["that", "payload"],
      );

  @override
  Uint8List crateApiJpakeG7JpakeSharedKey({required G7Jpake that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeG7JpakeSharedKeyConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeG7JpakeSharedKeyConstMeta =>
      const TaskConstMeta(debugName: "G7Jpake_shared_key", argNames: ["that"]);

  @override
  Uint8List crateApiJpakeAes8WithKey({
    required List<int> sessionKey,
    required List<int> data8,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(sessionKey, serializer);
          sse_encode_list_prim_u_8_loose(data8, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiJpakeAes8WithKeyConstMeta,
        argValues: [sessionKey, data8],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiJpakeAes8WithKeyConstMeta => const TaskConstMeta(
    debugName: "aes8_with_key",
    argNames: ["sessionKey", "data8"],
  );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Uint8List crateApiX25519X25519GeneratePrivateKey() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiX25519X25519GeneratePrivateKeyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiX25519X25519GeneratePrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "x25519_generate_private_key",
        argNames: [],
      );

  @override
  Uint8List crateApiX25519X25519PublicFromPrivate({
    required List<int> privateKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(privateKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiX25519X25519PublicFromPrivateConstMeta,
        argValues: [privateKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiX25519X25519PublicFromPrivateConstMeta =>
      const TaskConstMeta(
        debugName: "x25519_public_from_private",
        argNames: ["privateKey"],
      );

  @override
  Uint8List crateApiX25519X25519SharedSecret({
    required List<int> privateKey,
    required List<int> peerPublicKey,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(privateKey, serializer);
          sse_encode_list_prim_u_8_loose(peerPublicKey, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiX25519X25519SharedSecretConstMeta,
        argValues: [privateKey, peerPublicKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiX25519X25519SharedSecretConstMeta =>
      const TaskConstMeta(
        debugName: "x25519_shared_secret",
        argNames: ["privateKey", "peerPublicKey"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_G7Jpake => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_G7Jpake => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake;

  @protected
  G7Jpake
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return G7JpakeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  G7Jpake
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return G7JpakeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  G7Jpake
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return G7JpakeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  G7Jpake
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return G7JpakeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  G7Jpake
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return G7JpakeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  G7Jpake
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return G7JpakeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    G7Jpake self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as G7JpakeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    G7Jpake self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as G7JpakeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerG7Jpake(
    G7Jpake self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as G7JpakeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class G7JpakeImpl extends RustOpaque implements G7Jpake {
  // Not to be used by end users
  G7JpakeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  G7JpakeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_G7Jpake,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_G7Jpake,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_G7JpakePtr,
  );

  /// AES key-confirmation primitive (`encrypt8AES`): AES-128-ECB of the 8-byte
  /// input (doubled to a 16-byte block), returning the first 8 bytes. Used for
  /// opcodes 0x02/0x04. Key = the derived session key.
  Uint8List aes8({required List<int> data8}) =>
      RustLib.instance.api.crateApiJpakeG7JpakeAes8(that: this, data8: data8);

  /// Proof-of-possession (`0x0C`): sign SHA-256 of the sensor's 16-byte
  /// challenge (`challenge[2..18]`) with the Dexcom display key, returning a
  /// 64-byte raw `r‖s` ECDSA-P256 signature. (Juggluco `getchallenge`.)
  ///
  /// `display_key` is the 32-byte private key of the leaf display certificate
  /// (`getKeyC` in ecJPake.cpp, zero-padded). It is Dexcom's, so it is not in
  /// this source: Dart passes it in from the vendor keys (docs/VENDOR_KEYS.md).
  Uint8List popSign({
    required List<int> challenge,
    required List<int> displayKey,
  }) => RustLib.instance.api.crateApiJpakeG7JpakePopSign(
    that: this,
    challenge: challenge,
    displayKey: displayKey,
  );

  /// Round-1 payload (our key[0]) for `ExchangePakePayload` phase 0.
  Uint8List round1Payload() =>
      RustLib.instance.api.crateApiJpakeG7JpakeRound1Payload(that: this);

  /// Round-2 payload (our key[1]) for `ExchangePakePayload` phase 1.
  Uint8List round2Payload() =>
      RustLib.instance.api.crateApiJpakeG7JpakeRound2Payload(that: this);

  /// Our round-3 payload (`makeRound3Cert`) for `ExchangePakePayload` phase 2.
  /// Requires both sensor round-1 and round-2 to have been set.
  Uint8List round3Payload() =>
      RustLib.instance.api.crateApiJpakeG7JpakeRound3Payload(that: this);

  /// Store the sensor's round-1 (phase 0) cert. Returns whether its ZKP verifies.
  bool setSensorRound1({required List<int> payload}) => RustLib.instance.api
      .crateApiJpakeG7JpakeSetSensorRound1(that: this, payload: payload);

  /// Store the sensor's round-2 (phase 1) cert. Returns whether its ZKP verifies.
  bool setSensorRound2({required List<int> payload}) => RustLib.instance.api
      .crateApiJpakeG7JpakeSetSensorRound2(that: this, payload: payload);

  /// Store the sensor's round-3 cert and derive the shared session key.
  /// Returns the 16-byte AES-128 session key.
  Uint8List setSensorRound3({required List<int> payload}) => RustLib
      .instance
      .api
      .crateApiJpakeG7JpakeSetSensorRound3(that: this, payload: payload);

  /// The derived 16-byte session key (after `set_sensor_round3`).
  Uint8List sharedKey() =>
      RustLib.instance.api.crateApiJpakeG7JpakeSharedKey(that: this);
}
