// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_shared_key`, `encrypt8_aes`, `fill`, `from_bytes`, `hash_challenge`, `point_from_xy`, `point_uncompressed`, `point_x`, `point_xy`, `push_be_len`, `random_scalar`, `scalar_from_be`, `scalar_from_hex`, `to_bytes`, `verify`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`, `PCert`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Reconnect-path AES key confirmation using a previously-derived session key
/// (no J-PAKE needed). Same primitive as `G7Jpake::aes8`. Returns the 8-byte
/// AES-128-ECB block for opcodes 0x02/0x04.
Uint8List aes8WithKey({
  required List<int> sessionKey,
  required List<int> data8,
}) => RustLib.instance.api.crateApiJpakeAes8WithKey(
  sessionKey: sessionKey,
  data8: data8,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<G7Jpake>>
abstract class G7Jpake implements RustOpaqueInterface {
  /// AES key-confirmation primitive (`encrypt8AES`): AES-128-ECB of the 8-byte
  /// input (doubled to a 16-byte block), returning the first 8 bytes. Used for
  /// opcodes 0x02/0x04. Key = the derived session key.
  Uint8List aes8({required List<int> data8});

  /// Initialise with the sensor pairing code (the 4-character applicator code).
  /// Generates the two ephemeral keypairs (x1, x2).
  factory G7Jpake({required String pairingCode}) =>
      RustLib.instance.api.crateApiJpakeG7JpakeNew(pairingCode: pairingCode);

  /// Proof-of-possession (`0x0C`): sign SHA-256 of the sensor's 16-byte
  /// challenge (`challenge[2..18]`) with the embedded display key, returning a
  /// 64-byte raw `r‖s` ECDSA-P256 signature. (Juggluco `getchallenge`.)
  Uint8List popSign({required List<int> challenge});

  /// Round-1 payload (our key[0]) for `ExchangePakePayload` phase 0.
  Uint8List round1Payload();

  /// Round-2 payload (our key[1]) for `ExchangePakePayload` phase 1.
  Uint8List round2Payload();

  /// Our round-3 payload (`makeRound3Cert`) for `ExchangePakePayload` phase 2.
  /// Requires both sensor round-1 and round-2 to have been set.
  Uint8List round3Payload();

  /// Store the sensor's round-1 (phase 0) cert. Returns whether its ZKP verifies.
  bool setSensorRound1({required List<int> payload});

  /// Store the sensor's round-2 (phase 1) cert. Returns whether its ZKP verifies.
  bool setSensorRound2({required List<int> payload});

  /// Store the sensor's round-3 cert and derive the shared session key.
  /// Returns the 16-byte AES-128 session key.
  Uint8List setSensorRound3({required List<int> payload});

  /// The derived 16-byte session key (after `set_sensor_round3`).
  Uint8List sharedKey();
}
