// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_secret`

/// Generates a fresh 32-byte X25519 private key from the OS entropy source.
///
/// A pairing key is only ever used for one pod activation; reusing one across
/// pods would let a recovered key unlock a second pod's session.
Uint8List x25519GeneratePrivateKey() =>
    RustLib.instance.api.crateApiX25519X25519GeneratePrivateKey();

/// Derives the matching public key for a private key.
Uint8List x25519PublicFromPrivate({required List<int> privateKey}) => RustLib
    .instance
    .api
    .crateApiX25519X25519PublicFromPrivate(privateKey: privateKey);

/// Computes the shared secret between our private key and the pod's public key.
///
/// An all-zero result means the peer sent a low-order point, which forces a
/// known shared secret regardless of our key. That is rejected rather than
/// returned, so a spoofed pod cannot steer the pairing onto a key it chose.
Uint8List x25519SharedSecret({
  required List<int> privateKey,
  required List<int> peerPublicKey,
}) => RustLib.instance.api.crateApiX25519X25519SharedSecret(
  privateKey: privateKey,
  peerPublicKey: peerPublicKey,
);
